### ISSUE TITLE
Display the title property

### ISSUE THREAD

**Issue by djmtype** [paulirish/lite-youtube-embed#100]
Is there any way of accessing the video's title property without an api key, then display it as part of the button screen reader text for accessibility purposes?

**Comment by paulirish** [comment]
you can use the `playlabel` attribute, as described in the readme. this'll make the button label clear for assistive devices.

without an API key we can't get the video title automatically though. so you'll have to set that yourself.

also #88 is solving a different problem than i think you care about. (its more for sighted users).  but FYI anyway
