### ISSUE TITLE
Add eslint and stylelint configs / script

### ISSUE THREAD

**Issue by coliff** [paulirish/lite-youtube-embed#108]
I think it'd be good to add a `.stylelintrc` and a `eslintrc.json` to the projects root and add `lint-js` and `lint-css` tasks to package.json. We can use the recommended/standard configs for both. what do you think? I'd be happy to add a PR for this...

**Comment by paulirish** [comment]
i've been using prettier on this project so far and liking it. let's just do that.  i don't really want to block any PRs on basic linting stuff here. the codebase is too small to really go too hard. :)

for prettier i guess we just need a config file and an npm script. don't wanna do any hooks or w/e.

**Comment by coliff** [comment]
Great. I’m a fan of Prettier too, I’ll open a PR later today.
