### ISSUE TITLE
Can this generate a background video?

### ISSUE THREAD

**Issue by jiang-yuan** [paulirish/lite-youtube-embed#112]
Would you like to introduce an option with all the following features into your package?
like auto loop play, remove controls.
The demo and code:
https://codepen.io/adamgreenough/pen/bGrgoNb?editors=1100

**Comment by paulirish** [comment]
While I think this may be possible... I don't know why you'd use lite-youtube-embed for a background video that should start without user input. This component definitely requires user input before the video starts playing..
