### ISSUE TITLE
Vercel Usage

### ISSUE THREAD

**Issue by leerob** [paulirish/lite-youtube-embed#114]
Hey there! I saw you were still using a [now.json](https://github.com/paulirish/lite-youtube-embed/blob/master/now.json) file. Are you still utilizing Vercel? I'd be happy to make a PR to switch that over to `vercel.json` 😄 

Or alternatively, you can remove the file entirely if you would like comments from the Vercel bot.

**Comment by paulirish** [comment]
Yes please! :)
