### ISSUE TITLE
Mass convert youtube iframe to youtube-embed tag

### ISSUE THREAD

**Issue by griccitiello42** [paulirish/lite-youtube-embed#116]
Hello,

I am looking for the best solution to mass transform my HTML page video content into lite-youtube embed tags.
Example
```
<div class="videoWrapper">
<iframe frameborder="0" height="315" src="https://www.youtube.com/embed/xxxxxCODE?rel=0" width="560"></iframe>
</div>
```
into this

```
<div class="videoWrapper">
<lite-youtube videoid="xxxxxCODE" params="controls=1&modestbranding=2&rel=0&enablejsapi=1"></lite-youtube>
</div>
```
Do you have any suggestion to mass transform? (html data is in mysql database)
thanks

**Comment by paulirish** [comment]
Nope, thats beyond the support we can offer here. Best of luck!
