### ISSUE TITLE
I need two clicks to play video in Safari

### ISSUE THREAD

**Issue by zuzanasumlanskaSK** [paulirish/lite-youtube-embed#119]
Hi, 

I have an issue with lite-youtube-embed. 

When I open this [link in Safari ](https://paulirish.github.io/lite-youtube-embed/)(version 15.3), I need two clicks to actually play the video. 

Is that a bug or it is supposed to work like that? In other browsers it's fine.

Thanks and have a nice day

**Comment by danielbachhuber** [comment]
It looks like this is a duplicate of #6

**Comment by erikdemarco** [comment]
This occurs not just in safari. Chrome and opera mobile needs 2click as well

**Comment by paulirish** [comment]
dupe of #6
