### ISSUE TITLE
Autoplay doesn't seems to work

### ISSUE THREAD

**Issue by aLe-kLaus** [paulirish/lite-youtube-embed#120]
Hello,
I'm trying the use lite-youtube in an aplication and I'm trying to insure that the videos autoplay, here is the fiddle of how I was trying to make the video autoplay https://jsfiddle.net/aLe_kLaus/s5427y9n/65/, but I was't able to make it work at all.

**Comment by sarrim** [comment]
Anyone resolved that issue? I also can not autoplay the video loaded in my website

**Comment by sarrim** [comment]
Anyone resolved that issue? I also can not autoplay the video loaded in my website

<lite-youtube autoload style="" videoplay="" videotitle="" videoid="7VZxS5zu7w4" autoplay="1" params="controls=0&start=1&autoplay=1&modestbranding=2&rel=0&enablejsapi=1"></lite-youtube>

**Comment by paulirish** [comment]
dupe of #6
