### ISSUE TITLE
Centering the video element doesnt work

### ISSUE THREAD

**Issue by erikdemarco** [paulirish/lite-youtube-embed#121]
I want to center this video element created by lite-youtube-embed but it doesnt work, sometimes the video is gone.
I also try bunch of css here, still no success:
https://stackoverflow.com/questions/114543/how-to-horizontally-center-an-element

Any suggestion to center this video element responsively?

**Comment by Wayneb4788** [comment]
I have the same issue. I have tried various options including editing the CSS to horizontally center the embed but I am unable to make it work.

**Comment by tombo-coys** [comment]
I have acheived this by removing the max-width value that is set on the custom element, which allows the video element to fill the parent.

Not quite centering the element itself, but it works in my case.

`.wrapper > div > lite-youtube {
  max-width: unset;
}
`

**Comment by paulirish** [comment]
Thanks @tombo-coys

**Comment by nicks-crumpets** [comment]
For anyone using tailwind, use attribute `mx-auto` inside the `lite-youtube` tags:

```
<lite-youtube
  class="w-full mx-auto"
  videoid="goiWrNiaT0I"
  playlabel="Play: Crayon Physics Deluxe - Trailer HD">
</lite-youtube>
```

I don't 100% understand why this works, but it does, if anyone does let me know!
