### ISSUE TITLE
Ship a new release 🚢 

### ISSUE THREAD

**Issue by coliff** [paulirish/lite-youtube-embed#125]
Hey @paulirish !
It's been a long while since v0.2.0 was released, back in March 2021.

It'd be great to see a v0.3.0 release with all those [fixes and improvements which have been merged](https://github.com/paulirish/lite-youtube-embed/pulls?q=is%3Apr+sort%3Aupdated-desc+is%3Amerged) since then. There's a bunch of good PRs open too which can hopefully be reviewed & merged first.

**Comment by paulirish** [comment]
v0.3.0  is out

https://github.com/paulirish/lite-youtube-embed/releases/tag/v0.3.0
