### ISSUE TITLE
Time skipping option needed

### ISSUE THREAD

**Issue by josephmiller2000** [paulirish/lite-youtube-embed#129]
Is it possible to add time delay to the youtube frame videos? Because right now it is not possible.

for example 

https://www.youtube.com/watch?v=xBLsWs-cwgc&t=618s

**Comment by paulirish** [comment]
Yup. It just goes through the player params instead: https://github.com/paulirish/lite-youtube-embed#custom-player-parameters


```html
<lite-youtube videoid="xBLsWs-cwgc" params="start=618"></lite-youtube>
```
