### ISSUE TITLE
use isolated CE registration?

### ISSUE THREAD

**Issue by paulirish** [paulirish/lite-youtube-embed#13]
In #3, @Garbee separated out the `customElements.define()` call so the developer had control over it.

In a way this is kinda annoying... for example the dumb onload handler i had to do here: 

https://github.com/paulirish/lite-youtube-embed/blob/4fe639444118c7886aec3df9b77e51c665f80096/variants/pe.html#L25-L26

I'm considering putting that back in as part of the script, basically taking registration away from the developer. This also means the custom element class wouldn't necessarily need to be a global.

**Comment by paulirish** [comment]
Ah. https://justinfagnani.com/2019/11/01/how-to-publish-web-components-to-npm/ also recommends for the library to self-define.

@Garbee what was the reasoning you had?

**Comment by Garbee** [comment]
Oh, I just commented on #1 about this. Yea, I'm reversing course since the current norms everywhere are to self-define. PR coming in by the end of tomorrow.
