### ISSUE TITLE
ES Module

### ISSUE THREAD

**Issue by MCMattia** [paulirish/lite-youtube-embed#134]
Hi guys I am using sveltekit and lite-youtube-embed but I am getting the following error when I launch `pnpm run dev`. I don't know much of cjs and ES module. I am opening this issue to report the problem and hopefully somebody competent can handle it.

`lite-youtube-embed doesn't appear to be written in CJS, but also doesn't appear to be a valid ES module (i.e. it doesn't have "type": "module" or an .mjs extension for the entry point). Please contact the package author to fix.`

lite-youtube-embed works more or less in dev mode but not in production.

**Comment by Garbee** [comment]
The built file is not a module at all. There are no exports of any kind. It is a standalone script that needs to get dropped into the page and then used.

I'm sure on the specifics of what Sveltkit is doing and how you're trying to use it. Seems like a problem with the way you're trying to import the script into something else when it isn't feasible. Maybe a bare import would work, but that would still confuse a compiler most likely.

**Comment by mateomorris** [comment]
Used this successfully with Svelte: https://github.com/zamanruhy/svelte-lite-youtube-embed

**Comment by paulirish** [comment]
Duping this into #1 

The most obvious ways to publish this on NPM in a way that's bundler friendly result in sacrificing the web performance details. The most obvious part: The CSS should be bundled into your CSS.. it should not be added via clientside javascript.
