### ISSUE TITLE
Drop of Videos Indexed

### ISSUE THREAD

**Issue by Jacohun1** [paulirish/lite-youtube-embed#137]
Probably the same issue as dwsmart but as I am implementing this I have noticed my videos are being de-indexed. 
![image](https://user-images.githubusercontent.com/6316084/210593291-6580dc94-336e-40d5-a6f7-3e9171622c39.png)

**Comment by headerbidding** [comment]
Make sure that all your videos are playing and you didn't introduce a syntax error in the changeover.

**Comment by headerbidding** [comment]
I also noticed a de-indexing of videos on my site, but it started before I implemented lite-youtube-embed.

**Comment by SagaciousBen** [comment]
I have had a similar script running on my website for quite a few years. I have only just noticed that these pages don't register as 'video pages' on google search console. I only have one page on my site that does register as a video page and that's my sales page which has a full default youtube iframe embed.

Would you happen to know if your script shows that it is a video page? and if not would it be possible to look into whether there is a way to ad this signal without damaging pagespeed by loading a full embed?

So bizarre that google owns youtube google hates youtube embeds, and youtube refuses to develop efficient ones :/

**Comment by paulirish** [comment]
Yeah this lite-youtube-embed is basically just an image and play button before it's clicked on.  So.. Search Console isn't going to identify it as a video page.

**Comment by paulirish** [comment]
.... actually #105 has more discussion of this issue.. and a fix. and I just landed it

see https://github.com/paulirish/lite-youtube-embed/issues/105#issuecomment-1975289541 for more.

FIXED.

**Comment by Jacohun1** [comment]
@paulirish you're the best!
