### ISSUE TITLE
New tag release

### ISSUE THREAD

**Issue by mikemike** [paulirish/lite-youtube-embed#140]
Can you please issue a new release? There are a number of fixes in the `master` branch not in the latest published branch (0.2.0). Notable one for me is the fix for multiple iframes being fired ([here](https://github.com/paulirish/lite-youtube-embed/blob/master/src/lite-yt-embed.js#L138)).

I got around this by re-adding the repo directly instead of via an npm package. In other words:

```
npm i paulirish/lite-youtube-embed#master --save
```

or:
```
"dependencies": {
        ...
        "lite-youtube-embed": "github:paulirish/lite-youtube-embed#master"
    }
```

It would be much better if `npm i lite-youtube-embed` had those fixes though.

Happy to do the release if you're able to give relevant access to repo.

Thanks!

**Comment by comzeradd** [comment]
Comparing `master` with latest tag, looks like a lot of fixes have happened in the meantime.

https://github.com/paulirish/lite-youtube-embed/compare/v0.2.0...master

**Comment by hamkiti** [comment]
I also sympathize with this issue.
Creating a new tag clears this issue!

https://github.com/paulirish/lite-youtube-embed/issues/119

Best regards.

**Comment by hamkiti** [comment]
@paulirish
I also sympathize with this issue.
Creating a new tag clears this issue!

https://github.com/paulirish/lite-youtube-embed/issues/119

**Comment by shrpne** [comment]
@paulirish friendly reminder to update release

**Comment by paulirish** [comment]
v0.3.0  is out

https://github.com/paulirish/lite-youtube-embed/releases/tag/v0.3.0
