### ISSUE TITLE
Multiple mount

### ISSUE THREAD

**Issue by michalmatuska** [paulirish/lite-youtube-embed#143]
Hi all,
I found out big issue.
WebComponent doesn't take care about unmout method but what's worst are unwanted multiply mounts.
Simple DOM operation like appendChild start connected callback again.
Example here https://codepen.io/superkoders/pen/MWqJjQv
Result
![Liteyoutube double init test 2023-02-28 10-16-34](https://user-images.githubusercontent.com/597048/221809476-c08c4619-6ccb-4ba3-a9be-a066fd8f8620.png)

**Comment by paulirish** [comment]
This was fixed in [v0.1.2](https://github.com/paulirish/lite-youtube-embed/releases/tag/v0.1.2) which was 3 years ago...

To @michalmatuska and the folks +1'ing this issue.. do you know why you're using such old versions of this project?

**Comment by michalmatuska** [comment]
Hmm I would like to know it but is too long time know. I am not sure now what project it was. Sorry. It could be some issue with NPM or my fault.
