### ISSUE TITLE
Failed to execute 'postMessage'

### ISSUE THREAD

**Issue by bsastregx** [paulirish/lite-youtube-embed#147]
Hello, greetings.

On mobile, the following error is showing in the console:

`
Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://www.youtube.com') does not match the recipient window's origin ('https://lite-youtube-embed.netlify.app').
`

[You can test it here](https://lite-youtube-embed.netlify.app/)

Any help on how to fix this will be much appreciated.

**Comment by paulirish** [comment]
I don't see this error on your test page anymore. 

Was it coming from the l-yt-e script or from youtube's js?

**Comment by paulirish** [comment]
Ah nevermind. It doesn't go that codepath unless its mobile or safari.

yeah this is expected. nothing is wrong. 


<img width="1047" alt="image" src="https://github.com/paulirish/lite-youtube-embed/assets/39191/ff2c6192-c36d-4596-9f17-d324aa66860a">
