### ISSUE TITLE
Display a title on the video thumbnail

### ISSUE THREAD

**Issue by ehakram** [paulirish/lite-youtube-embed#150]
From my understanding, there is no way to display a title on a video thumbnail.

Current behaviour:
![image](https://user-images.githubusercontent.com/23341378/235885243-d9cbdab8-1775-4824-ab61-278350525165.png)
Wanted behaviour:
![image](https://user-images.githubusercontent.com/23341378/235885847-463ac54a-e491-4fc6-82e7-a15dbb8026dd.png)

I am ok with the title needing to be set manually via a <lite-youtube> tag parameter.

Please let me know If there is a way to achieve this, or anything similar,  that I am not aware of.

From my understanding, this pull request does what I need. If true, can you merge it?
https://github.com/paulirish/lite-youtube-embed/pull/88

Thanks

**Comment by terryzfeng** [comment]
Can confirm that #88 works great. I'm currently using it in my own implementation of this code.

**Comment by paulirish** [comment]
fixed by #88
