### ISSUE TITLE
NPM version is outdated

### ISSUE THREAD

**Issue by TacsiHun** [paulirish/lite-youtube-embed#156]
Hey Thanks for this solution! What I wanna say is not really a bug or anything, but maybe it's worth mentioning that the npm version is outdated and does not contain some bugfixes. I had issues that are already solved, so I changed to github version.

**Comment by paulirish** [comment]
v0.3.0  is out

https://github.com/paulirish/lite-youtube-embed/releases/tag/v0.3.0
