### ISSUE TITLE
A more accurate YouTube play button

### ISSUE THREAD

**Issue by chuanqisun** [paulirish/lite-youtube-embed#16]
The existing button is a implemented with the CSS box model. The actual YouTube has subtle curvature around the box, which is very hard to achieve with pure CSS. 

Consider replace the CSS with an SVG, either as background image or as HTML. I'm happy to assist by creating a PR if you are ok with it. @paulirish

**Comment by paulirish** [comment]
explored in #8 and #17 and #39 

eventually fixed in #39 


cheers
