### ISSUE TITLE
Will it be counted as views on YouTube?

### ISSUE THREAD

**Issue by Ui6oooooo** [paulirish/lite-youtube-embed#160]
Insert lite-youtube-embed on the website. If someone clicks on the video and plays it, will this be counted as a play amount in YouTube?

**Comment by ErikThiart** [comment]
Same question, is this counted by youtube as a view?

(does not appear so)

**Comment by paulirish** [comment]
I don't believe so. Probably because we use the nocookie domain.

**Comment by kirupa** [comment]
@paulirish - is there a way to customize the embed to not use the "nocookie" domain so that embedded views will count on YouTube's view count?

**Comment by alexlance** [comment]
So the views will get counted again if I (locally) invert this patch: https://github.com/paulirish/lite-youtube-embed/pull/18/files 

?

**Comment by kirupa** [comment]
@alexlance - that's what I did, and it seemed to do the trick.
