### ISSUE TITLE
sometime no image loaded

### ISSUE THREAD

**Issue by Jan-dax** [paulirish/lite-youtube-embed#162]
Sometime i put link from youtube and have only gray background, but no image. I think that because is no image in HD, only SD, 
Do you know something about this problem?

**Comment by paulirish** [comment]
I haven't found cases where the image is not available in `hqdefault.jpg`. 

But.. if you run into this you can set your own poster image https://github.com/paulirish/lite-youtube-embed#custom-poster-image
