### ISSUE TITLE
Early click on Progressively Enhanced version directs user to youtube.com

### ISSUE THREAD

**Issue by page200** [paulirish/lite-youtube-embed#165]
When I go to https://paulirish.github.io/lite-youtube-embed/variants/pe.html and click on the video before the page says "Script complete.", the browser leaves the page and goes to the video on youtube.com

**Comment by paulirish** [comment]
Yup exactly.

That's progressive enhancement (aka graceful degradation).

The test page adds an artificial 2 second delay so you can really tell the difference.

Without PE, you'd click on the video and nothing would happen.
