### ISSUE TITLE
How can we keep the lower quality preview?

### ISSUE THREAD

**Issue by FANMixco** [paulirish/lite-youtube-embed#175]
I like the idea of showing the best quality preview, but it consumes more bandwidth. Is there an option that allows you to load only the lower quality images? Or should we use an older version? Thanks.

**Note:**
If you are asking, why would you want or need that? If you're loading the YouTube video on a mobile, it should not load the highest quality since it consumes more bandwidth than needed. That's great for desktops or tablets, but not for smartphones or watches.

**Comment by paulirish** [comment]
Assuming you're talking about the new 'higher resolution webp' upgrade from [v0.3.1](https://github.com/paulirish/lite-youtube-embed/releases/tag/v0.3.1)

What's actually funny is the higher resolution webp actually comes LESS bandwidth than the smaller jpeg. (In all cases that I've come across, at least).

For the moment you'd need to use an older version yeah. 

TBH I plan to change the default: https://github.com/paulirish/lite-youtube-embed/issues/187
