### ISSUE TITLE
v0.3.2 Release

### ISSUE THREAD

**Issue by coliff** [paulirish/lite-youtube-embed#179]
The npm package was updated to v0.3.2 last month (https://www.npmjs.com/package/lite-youtube-embed?activeTab=versions) but it hasn't been tagged in GitHub yet:
https://github.com/paulirish/lite-youtube-embed/releases

So anyone subscribed to releases for this package won't have been notified about it and we can't see a changelog.
@paulirish - Could you add that please? :-)

**Comment by paulirish** [comment]
@coliff thx christian! appreciate it :)    https://github.com/paulirish/lite-youtube-embed/releases/tag/v0.3.2

i probably skipped it because of the reason i wrote in there but... still it's worth being explicit.
