### ISSUE TITLE
Query and display title of YouTube video

### ISSUE THREAD

**Issue by brandonpeat** [paulirish/lite-youtube-embed#184]
I'm trying to achieve an end result like this demo:
https://paulirish.github.io/lite-youtube-embed/variants/title.html

Per the readme, my understanding is that the title is manually specified:

```
If you want to display a title prior to loading the full embed, set the title attribute:
<lite-youtube videoid="ogfYd705cRs" title="Keynote (Google I/O '18)"></lite-youtube>
```

I'd like to generate the title automatically from the YouTube video, the same way the poster image is loaded automatically. Is that possible with this script? Potential feature request?

**Comment by paulirish** [comment]
@brandonpeat nah sorry. If you want a title in there, you have to set it manually. That data isn't available with any API we have access to.  

So.. I think this would probably be a feature for your CMS so it could do that API work and hand it off.
