### ISSUE TITLE
MIME text/html not supported stylesheet

### ISSUE THREAD

**Issue by Samrridh** [paulirish/lite-youtube-embed#185]
![image](https://github.com/user-attachments/assets/fc3979c8-4ca1-48b6-b555-a79e361e4965)
mime type not supported. I am using an astro framework, and css is not applied to my frame, just this black dot.
![image](https://github.com/user-attachments/assets/15f92b2a-a92e-4c1a-81c2-46dc1713753c)
though it is applied in the localhost, but i guess after build it is not able to use the css

sidenote: i installed using npm and not the other way

**Comment by Samrridh** [comment]
Refused to apply style from 'https://demowebsite.xyz/node_modules/lite-youtube-embed/src/lite-yt-embed.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.

This issue is being consoled

**Comment by Garbee** [comment]
This is your web server not properly serving the file. It needs to appropriately set the [Content-Type](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Type) header for served files. How this is done depends on the web server. So please consult the documentation of whatever host you're using for further guidance, as this is not an issue with the yt-lite component itself.
