### ISSUE TITLE
Playback quality setting

### ISSUE THREAD

**Issue by thisisjamessmith** [paulirish/lite-youtube-embed#186]
Has anyone else noticed that when using lite-youtube, the video quality takes a few seconds (around 8s on my fast home connection) before it 'upgrades' you to the highest quality version? Any workarounds to make this more instantaneous? Playing the same video on YouTube has it instantly at the highest quality.

**Comment by paulirish** [comment]
I can't imagine that behavior's specific to lite-youtube.... the same should apply when using youtube's normal iframe embed.

Beyond that.. I don't know why, but it is curious. Youtube definitely has more network quality info from your browser in the .com case that would allow them to choose a better/higher starting resolution in their DASH setup.  So I'd guess it's that. But someone might be able to figure out more with a deepdive investigation session.

**Comment by thisisjamessmith** [comment]
Thanks for your fast reply Paul. Yeh, I can confirm it's the same with a regular iframe embed, sorry should have checked that before posting here! It's quite odd, I've never noticed this issue before despite many years of embedding various clients' videos, both with and without your facade. It's also seemingly difficult to consistently replicate, and is also inconsistent across different browsers.

**Comment by paulirish** [comment]
It's possible that the youtube-nocookie origin is hurting this. You might wanna try tweaking that origin to see if it has any effect. (But... the regular iframe embed uses the real cookied origin, so.... shrug)
