### ISSUE TITLE
PageSpeed penalizes <lite-youtube> for removing href from <a>

### ISSUE THREAD

**Issue by arturhonores** [paulirish/lite-youtube-embed#189]
When using <a> inside <lite-youtube>, as shown in the following example:

`<lite-youtube videoid="goiWrNiaT0I" style="background-image: url('https://i.ytimg.com/vi/goiWrNiaT0I/hqdefault.jpg');">
  <a href="https://youtube.com/watch?v=goiWrNiaT0I" class="lty-playbtn" title="Play Video">
    <span class="lyt-visually-hidden">Play Video: Crayon Physics Deluxe - Trailer HD</span>
  </a>
</lite-youtube>`

PageSpeed penalizes the component with the message: "Links are not traceable". I found a temporary solution by adding role="button", but I’d like to know if it’s necessary to keep using the <a> tag since the code removes the href in this line:

`playBtnEl.removeAttribute('href');`

**Comment by paulirish** [comment]
That was fixed in #183 

Latest release v0.3.3 will sort you out.
