### ISSUE TITLE
Field "thumbnailUrl" is missing, cannot be added automatically

### ISSUE THREAD

**Issue by bangdang1908** [paulirish/lite-youtube-embed#190]
I'm having an error with the Lite Youtube Embed thumbnailUrl

<img width="692" alt="Screenshot 2024-11-30 093942" src="https://github.com/user-attachments/assets/27d2601b-d8c0-4a46-99a5-06239995712a">
<img width="1558" alt="Screenshot 2024-11-30 094027" src="https://github.com/user-attachments/assets/5a851db9-fe63-422f-b45f-e095c695fff0">

I used Rank Math SEO Plugin and Yoast SEO test but it didn't work. I think the problem is because the plugin takes thumbnailUrl from the structure: Video Thumbnail: %post_thumbnail%

But Lite Youtube Embed has the structure "background-image": 

<lite-youtube videoid="goiWrNiaT0I" style="background-image: url('https://i.ytimg.com/vi/goiWrNiaT0I/hqdefault.jpg');"></lite-youtube>

How do I solve this problem?

Looking forward to hearing from you! Thanks a lot team!

**Comment by paulirish** [comment]
@seezer are you my wordpress plugin buddy?

**Comment by paulirish** [comment]
@bangdang1908 sorry this repo is for the core script. For the wordpress plugin I think you'll want to file something here https://wordpress.org/support/plugin/lite-embed-for-youtube/
