### ISSUE TITLE
offer webp images

### ISSUE THREAD

**Issue by ThaUnknown** [paulirish/lite-youtube-embed#191]
youtube offers thumbnails in webp format, while they are 1/2 the size, they don't exist for older videos, it might however be worth considering it

https://i.ytimg.com/vi_webp/pYI9SQvXpiE/sddefault.webp

however as shown in the thumbnail code, it's possible to detect which thumbnails are supported, for example:

```ts
  const sizes = ['hq720', 'sddefault', 'hqdefault', 'mqdefault', 'default']
  let sizeAttempt = 0

  function verifyThumbnail (e: Event) {
    if (!isYoutube) return
    const img = e.target as HTMLImageElement
    if (img.naturalWidth === 120 && img.naturalHeight === 90) {
      img.src = `https://i.ytimg.com/vi/${id}/${sizes[sizeAttempt++]}.jpg`
    }
  }
  img.onload = verifyThumbnail
  img.src = `https://i.ytimg.com/vi/${id}/${sizes[sizeAttempt++]}.jpg`
```
and the same thing could be expanded to check for webp images

**Comment by paulirish** [comment]
take a read on #187 .. i think it covers what you're getting at here.

**Comment by ThaUnknown** [comment]
ah yes
