### ISSUE TITLE
make it responsive

### ISSUE THREAD

**Issue by Garbee** [paulirish/lite-youtube-embed#2]
Looking at the element it creates an embed with a hard-coded size. By allowing custom attributes to be used to give a size (and handle their changing events) we can allow developers to get the size they need seamlessly.

While carrying this out, we'll follow the [best practices for custom elements](https://developers.google.com/web/fundamentals/web-components/best-practices) where applicable.

**Comment by paulirish** [comment]
Yah this seems required. Web.dev used a variant on my approach which handled dimensions better than me.

**Comment by paulirish** [comment]
web.dev uses this padding-top trick (which is written explicitly for the youtube case) https://blog.theodo.com/2018/01/responsive-iframes-css-trick/


although i like chris's adaptation in https://css-tricks.com/responsive-iframes/
