### ISSUE TITLE
Extra params (like start and end times)

### ISSUE THREAD

**Issue by smartcorestudio** [paulirish/lite-youtube-embed#20]
It's not an issue, just a feature request. Could you consider adding support for extra URL params, like
`<iframe ... src="https://www.youtube.com/embed/${this.videoId}?autoplay=1&start=10&end=30"</iframe>`

I think it can look something like:
`<lite-youtube videoid="..." params="start=10&end=30"></lite-youtube>`

**Comment by paulirish** [comment]
there's been a few more issues/PRs about this:

* #29 and #38 wanting start time (cc @JuanitoFatas @pavelloz)
* #33 for general extra settings (cc @mkjeldsen)

-----------------

I think @smartcorestudio's proposed solution is both flexible and means `lite-youtube-embed` doesn't have to get bloated to support each feature that the iframe does.

So the idea is make use of a single attribute on our element. Its value will be added into the YT iframe `src`'s query params.

```html
<lite-youtube videoid="..." params="start=10&end=30"></lite-youtube>
```


or to use a LOT of them

```html
<lite-youtube videoid="..." params="start=10&end=30&modestbranding=2&rel=0&enablejsapi=1&origin=http://lol.com"></lite-youtube>
```

--------------

I like using an attribute called `params`. I can think of a few alternatives, but I like this the best.

Thoughts?

**Comment by pavelloz** [comment]
Seems like a good solution to all current and possible future param-related feature requests anyone might have :)

PS. Sorry for duplicated issue

**Comment by Garbee** [comment]
I'll make sure we get this `params` attribute in nice and tidy with PR #28 when I clean it up this weekend (or tomorrow morning possibly. Tight on time tonight.) It's a super good way to give "full" support without building out attributes for every parameter.

**Comment by laukstein** [comment]
@paulirish, don't you think it would make more sense to simplify it with `url` param containing whatever (embed or not) YouTube link with or without extra params, like:

1. ~`id=ogfYd705cRs` (old format)~
2. `url="https://www.youtube.com/watch?v=ogfYd705cRs"` (new format)
3. `url="https://www.youtube.com/watch?time_continue=10&v=ogfYd705cRs&feature=emb_logo"` (with params)
4. `url="https://www.youtube.com/embed/ogfYd705cRs?autoplay=1&start=10&end=30&modestbranding=2&rel=0&enablejsapi=1&origin=https://github.com"` (pasted from embedded iframe, plus extra params)

`<lite-youtube>` could analyze `url` and parse it however decided.

I would even propose to change `lite-youtube` to something like `video-embed` allowing to handle videos from multiple video hosts, YouTube, Vimeo, etc. Here what I mean (maybe can handle without closing tag or like `<lite-video url=""/>`) :

1. `<video-embed url="https://www.youtube.com/watch?v=ogfYd705cRs">`
2. `<video-embed url="https://vimeo.com/270506902">`
3. `<video-embed url="https://www.dailymotion.com/video/x209qoh">`

**Comment by pavelloz** [comment]
^ This seems like a much bigger task (including renaming and changing purpose of the whole project) than forwarding `params` to the url ;-) 

PS. lite-vimeo-embed: https://github.com/luwes/lite-vimeo-embed

**Comment by lborgman** [comment]
Is there any problem with just adding "params=..." now for the <lite-youtube> element? What could go wrong?

**Comment by justinribeiro** [comment]
Cheers @paulirish for the note on that PR. That unified `params` approach works pretty well in practice for a case like this (at least in my experience building other not-so-public web components for corps). Maximum flexibility with least amount of element API churn.

**Comment by paulirish** [comment]
fixed by https://github.com/paulirish/lite-youtube-embed/pull/51 (which just landed. shipping in 0.1.0)

**Comment by paulirish** [comment]
update: `lite-youtube-embed@0.1.0` published
