### ISSUE TITLE
Link to React version at bottom of readme?

### ISSUE THREAD

**Issue by karlhorky** [paulirish/lite-youtube-embed#22]
Hey @paulirish, thanks for this, looks really cool!

Just testing the waters - not looking to start a flame war or anything:

For React users, would you be open to linking to the React version of this at the bottom of the Readme?

**Comment by paulirish** [comment]
Hey man!  Been a while. 

Yeah that sounds cool. You could also link up justinriberio's and also maybe calibre's new chat widget

**Comment by andrewvasilchuk** [comment]
@paulirish, can you, please, also provide a link for Vue.js users?
https://github.com/andrewvasilchuk/vue-lazy-youtube-video
I have made a similar component with a bunch of `slots` and `props`

**Comment by paulirish** [comment]
@andrewvasilchuk can you give me a PR that links both of these?

**Comment by isaacl** [comment]
I haven't published this yet, but I did a  pure vue v3/ts port here:
https://gist.github.com/isaacl/d25e88efae01d95599972e250f056ac8

**Comment by kylemocode** [comment]
I make a react version, and publish it as a npm package.
I will improve its feature recently.

https://github.com/kylemocode/react-lite-yt-embed

**Comment by karlhorky** [comment]
@kylemocode I've opened #71 that should close this issue now :)

**Comment by jamaluddinrumi** [comment]
> I haven't published this yet, but I did a pure vue v3/ts port here: https://gist.github.com/isaacl/d25e88efae01d95599972e250f056ac8

slick 😀
