### ISSUE TITLE
[Question] Change video id

### ISSUE THREAD

**Issue by guillermo7227** [paulirish/lite-youtube-embed#23]
Can I change the video id and make it play the new video after rendered?

**Comment by Garbee** [comment]
Not currently. I have PR #28 open which is a basic first-pass at allowing for this to work.

**Comment by paulirish** [comment]
@guillermo7227 i know it's been a while.. but i'm interested in understanding this usecase a little more..

presumably you have something like a ... social video/music jukebox.. and new videos play often.. so you'd want to change the video id from script?

it seems like you'd also need to know when the current video finished.. right?

is there another usecase i'm not considering?

**Comment by Garbee** [comment]
There could also be the case of say a video course. A list of available videos would show somewhere on the page. When one that isn't active is selected, it updates the same video embed to change the video stream rather than destroying and creating a new node.

**Comment by RentecErich** [comment]
In case anyone needs to know this, as a work around, you can destroy the lite-youtube element and create another one in its place with the new videoid to get this to work.  I tried updating the attr using setAttribute and then using the attributeChangedCallback in the class, but couldnt get it to work.  But the above work around got me where I needed to be.

**Comment by paulirish** [comment]
Yeah I prefer you just make a new one, like what @RentecErich suggests. 

Early on we had a version which reacted to changing attributes, but it gets complicated. For now, this is out of scope for this project.
