### ISSUE TITLE
Fallow spec and use HTML standard attributes data-*

### ISSUE THREAD

**Issue by laukstein** [paulirish/lite-youtube-embed#30]
Spec: JavaScript [`HTMLElement.dataset`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLOrForeignElement/dataset), HTML [`data-*`](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/data-*).

Replace `videoid` with `data-videoid` and https://github.com/paulirish/lite-youtube-embed/pull/29 `startTime` with `data-starttime` (notice: attributes should be in lowercase). If you like can use instead `data-video-id` (accessible in `HTMLElement.dataset.videoId`) and `data-start-time`. Personally I would prefer shorter `data-id` and `data-time`. Element `<lite-youtube>` already makes clear that it is related to YouTube making understandable to what **id** refers.

**Comment by Garbee** [comment]
Data attributes are for non-custom elements. When you have custom elements (as this is providing) making up your own top-level attributes is 100% a-OK and in fact encouraged.

Ref: [Custom element spec core concepts](https://html.spec.whatwg.org/multipage/custom-elements.html#custom-elements-core-concepts)

> Any namespace-less attribute that is relevant to the element's functioning, as determined by the element's author, may be specified on an autonomous custom element, so long as the attribute name is XML-compatible and contains no ASCII upper alphas.

The component is currently 100% in specification alignment and will continue to be so.

**Comment by laukstein** [comment]
> contains no ASCII upper alphas.

Is it about uppercase chars? If yes then #29 `startTime` is invalid.

**Comment by Garbee** [comment]
Fair point and nice catch. However we don't need to shift over to using data attributes to fix that problem.

**Comment by paulirish** [comment]
thanks for chiming in @laukstein 

we'll keep the `data-` prefix off, but definitely keep them all lowercase.

and @laukstein i'd love your 👍 if you like the plan in https://github.com/paulirish/lite-youtube-embed/issues/20#issuecomment-567168197
