### ISSUE TITLE
<lite-vimeo>

### ISSUE THREAD

**Issue by luwes** [paulirish/lite-youtube-embed#34]
My apologies for jumping on this so quickly but I thought it was a very cool project (added the Apache-2.0 license mentioned in #31) I started a fork for the Vimeo player which has some small improvements I think around configuration and including CSS in the JS bundle unless you decide to go a different route. would be cool to have no need for build tools but not sure if that's doable.

Feel free to close this issue, just wanted to ping here. Cheers!

Link: https://github.com/luwes/lite-vimeo-embed

**Comment by paulirish** [comment]
@luwes that's badass. can you give me a PR to add this to the readme?

**Comment by luwes** [comment]
Will close this one here, thanks @paulirish! 🙌
