### ISSUE TITLE
Consider using <img> instead of background for poster

### ISSUE THREAD

**Issue by haggen** [paulirish/lite-youtube-embed#37]
I think the video poster is part of the content and therefore should exist as an actual `<img>` element in the page instead of background. Of course that would also require an `alt` description to be provided. What do you think?

**Comment by Garbee** [comment]
My personal context on this is, the poster isn't the primary content. It is supplemental for the overall appearance to be closer to the regular embed. So it does feel like it belongs in the CSS more.

The purpose of the embed is not to provide the poster image to a user. It is to provide a rapidly rendered action to the page which can be replaced with the video embed itself. Therefore it is not primary content and isn't necessarily needed an in-markup image element.

If there is any supporting accessibility documentation to move the needle further in either direction then I'd love to read over it to consider. However short of that I don't see why we'd want to switch from what we have now unless it is somehow (non-marginally) faster as well.

**Comment by haggen** [comment]
@Garbee You make good points, but I'd argue that the poster is a stand-in for the primary content, which makes it content nonetheless, at least until an interaction is made. You could say it's just a link to the video and text would be enough, but as the saying goes, a picture carries much more information and nuance than text. A lot of videos use the poster as hook to the video content. From the perspective of crawlers and assistive technology a link could, at most, be parsed, have some meaning extracted and be translated. But an image could be described to a blind person, analyzed and have its content categorized and even connected back to the original video. Plus if the video doesn't load, having the image there is the next best thing, content wise.

**Comment by paulirish** [comment]
fwiw the actual youtube embed doesn't show the poster image as an `<img>`.

in practical terms it would add a lot of complexity to the responsive layout we support.

and i think its semantic wins actually dont convey into actualized user benefit.


i think this is really raising the question: "what is the ideal accessibility experience for a (unplayed) video embed?"  i think that's a great question that i don't know the answer to. but i assume that the answer is quite involved.  i've filed #40 to find out
