### ISSUE TITLE
Implement ideal accessibility

### ISSUE THREAD

**Issue by paulirish** [paulirish/lite-youtube-embed#40]
forked from #37 

The question is "what is the ideal accessibility experience for a (unplayed) video embed?" 

How should it be made accessible to AT like screenreaders?

------------

First, the play button should definitely be a semantic button (#9), but I suppose there are other opportunities, like a general `aria-label` on the parent container, etc.

My quick googling points to these resources:

* https://adrianroselli.com/2017/08/inaccessible-youtube-embeds.html
* https://github.com/videojs/video.js/pull/3227/files

But i imagine there's more.

**Comment by adamjohnson** [comment]
Having a `title` tag on `<iframe>` elements is [required by WCAG Level A 4.1.2](https://www.w3.org/TR/WCAG20-TECHS/H64). This would be good to implement for accessibility. eg:

```html
<iframe title="YouTube Video: Keynote (Google I/O '18)" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen="" src="https://www.youtube-nocookie.com/embed/ogfYd705cRs?autoplay=1"></iframe>
```

Also, removing depreciated presentational attributes like `frameborder` is a good idea. Some accessibility checkers ([Siteimprove](https://siteimprove.com/en-us/core-platform/integrations/browser-extensions/)) flag those as a [WCAG Level A 1.3.1 error](https://www.w3.org/TR/WCAG20-TECHS/G140). Note: this does rely on CSS having `iframe { border: 0; }` to remove the browser default border around `<iframe>`'s.
