### ISSUE TITLE
`getAttribute()` in constructor

### ISSUE THREAD

**Issue by luwes** [paulirish/lite-youtube-embed#44]
Just a heads up, I fixed a small bug in `lite-vimeo`.

`this.getAttribute()` should not be called in the custom element constructor as it's possible the attribute is not defined yet at that point. happens when the script tag comes before the `<lite-youtube>` element.

https://github.com/luwes/lite-vimeo-embed/commit/10f31db31309e8e7ced4b6a2bc49816b3456f79b

https://stackoverflow.com/a/42251436/268820

**Comment by Garbee** [comment]
Yup, working on this in #28. Thanks for the details as to why this practice should be discouraged though, useful to have written somewhere.
