### ISSUE TITLE
How to add playlists

### ISSUE THREAD

**Issue by MANICX100** [paulirish/lite-youtube-embed#47]
I can't work out how to add playlists if possible. :)

If not please can this be added then all the embeds across my site can be replaced.

**Great project thanks**

**Comment by Garbee** [comment]
Currently the URL used is for a singular video only. If @paulirish doesn't mind tweaking it to allow the other types of URLs, I already thought of two paths to handle it. But doing so will increase the complexity by a degree for attribute cross-checks.

**Comment by paulirish** [comment]
Yeah this is currently unsupported. 

It looks like it might be pretty easy... https://support.google.com/youtube/answer/171780?hl=en

.. but I'm going to defer for now.

**Comment by BlackeCZ** [comment]
Any progress? Even tho it should be easy, I wasn't able to set it up. :(

**Comment by kylegordy** [comment]
Adding playlist support would really help me out also 🤞

**Comment by paulirish** [comment]
This project won't support playlists but https://github.com/justinribeiro/lite-youtube does. Good luck!
