### ISSUE TITLE
lite-youtube-embed Implementation in wordpress

### ISSUE THREAD

**Issue by Abuki121** [paulirish/lite-youtube-embed#49]
Hello.
On my site in the records a lot of videos are added from youtube !! How to optimize already uploaded videos to a site using your plugin?
for this you need to write an additional script that would find the id in the pages from the youtube player code and add them to < lite-youtube  videoid = " Id_video" > </ lite-youtube > ?
Please tell me how to optimize the videos already added to the site .. I have a lot of them on the site !!

**Comment by mihdan** [comment]
@Abuki121, You can use our plugin [Lite YouTube Embed for WordPress](https://wordpress.org/plugins/mihdan-lite-youtube-embed/)
