### ISSUE TITLE
Please add a link to a test example to readme.md

### ISSUE THREAD

**Issue by lborgman** [paulirish/lite-youtube-embed#52]
I found a trouble when testing my version on mobile Chrome. I thought I might have made some stupid mistake and wanted to see how the original version worked. I could not find any test example here. 

There might be some example, but I have no idea how to find it. Please link to a test example in readme.md.

**Comment by Garbee** [comment]
https://paulirish.github.io/lite-youtube-embed/  -- The link is in the description of the repo. We should still get this into the readme though somehow so it is called out better. Thank you for the request.
