### ISSUE TITLE
Tag a release?

### ISSUE THREAD

**Issue by staabm** [paulirish/lite-youtube-embed#58]
What is open? Can we get a mvp release?

**Comment by paulirish** [comment]
@Manzurkds can you add me to the npm package you published ? :) 

https://www.npmjs.com/package/lite-youtube-embed

this is me: https://www.npmjs.com/~paulirish

**Comment by staabm** [comment]
ohh I didn't realize that its already published on npm (since no tags/releases are contained in the repo on github)

**Comment by staabm** [comment]
friendly ping @Manzurkds

**Comment by Manzurkds** [comment]
@staabm Ohh sorry, I got caught up in some work, missed this. What exactly you guys need, just want me to add @paulirish to the package?

**Comment by staabm** [comment]
@Manzurkds no worries. I guess adding paul would be enough, so github could automatically mirror releases on npm and we could start consuming the package from a "official" source

**Comment by Manzurkds** [comment]
@staabm @paulirish Done👍

**Comment by paulirish** [comment]
thanks so much @Manzurkds !

  **lite-youtube-embed@0.0.1 is out**

 probably going to ship another release or two pretty soon.
