### ISSUE TITLE
Access to image blocked by CORS policy

### ISSUE THREAD

**Issue by PaulMartinsen** [paulirish/lite-youtube-embed#59]
In Chrome, I get CORS errors in the console using this plugin:
`Access to image at 'https://i.ytimg.com/vi/_2aH3Z7YRZ4/hqdefault.jpg' from origin 'https://www.megunolink.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

Maybe YouTube is indicating they don't want their images to be used this way? The thumbnail is present when I scroll the video into view, so I'm a bit unclear whether this is a real problem or not. 

As a solution, I added a poster attribute to a hosted image by replacing
``this.posterUrl = `https://i.ytimg.com/vi/${this.videoId}/hqdefault.jpg`;``
with 
`this.posterUrl = this.getAttribute('poster'); `
in `lite-yt-embed.js`

Then the tag becomes:
`<lite-youtube videoid="_2aH3Z7YRZ4" poster="https://www.megunolink.com/wp-content/uploads/2020/06/introvideothumbnail.jpg" ></lite-youtube>`

**Comment by Ahrengot** [comment]
I ran into this same issue, but only when running on localhost. The images still loaded for me, but I got that same CORS error in the console.

**Comment by PaulMartinsen** [comment]
For me, it was on a live site. I don't understand enough about CORS to know if it is an important problem or not. Feel free to close the issue if it isn't worth solving :).

**Comment by pavelloz** [comment]
Yeah, Lighthouse is pointing it as two separate issues

Console error 
![image](https://user-images.githubusercontent.com/546845/93093354-df503f80-f6a0-11ea-9f05-231364ada49c.png)

Preload image not used warning
![image](https://user-images.githubusercontent.com/546845/93093442-fbec7780-f6a0-11ea-8e39-070c754fc690.png)
