### ISSUE TITLE
Achieve "Gold Standard" baseline

### ISSUE THREAD

**Issue by Garbee** [paulirish/lite-youtube-embed#62]
Ref 1: https://github.com/webcomponents/gold-standard/wiki
Ref 2: https://developers.google.com/web/fundamentals/web-components/best-practices

This is more of a meta-issue to discuss what overall goals we want to go after. Then the individual bits we wish to go after can be broken down into their own sub-issues for PRs to go against.

Does anyone in the community have any alternative recommended guidelines? Particularly interested in anything that conflicts with the guiding points laid out in gold-standard.

For any set of goals, individual issues should be opened describing it and a proposed solution. From there we can try to have some discussion before anyone digs heavy into the coding side.

The goal here, is to provide a baseline element that works along the lines of what the community expects from web components. While preserving the heavy focus on overall performance. With each individual goal to build up to this, the performance impacts need to be kept in mind.

**Comment by paulirish** [comment]
I'm gonna close this for now.. until theres something more actionable. I'm decently okay with how it's done as a web component. But.. i think if i were to revisit it again.. i'd probably dig into the recent posts about "html web components" and this great post by Zach https://www.zachleat.com/web/a-taxonomy-of-web-component-types/
