### ISSUE TITLE
Using both lyt- lty- prefixes

### ISSUE THREAD

**Issue by paulirish** [paulirish/lite-youtube-embed#65]
Whoops I used both!  My bad

`lyt-` is probably good. This is arguably a breaking change. :/

**Comment by Garbee** [comment]
It is breaking, but it's still a non-stable version so it's safe to break on any version bump. We should call it out in a changelog though.

**Comment by theRealPadster** [comment]
Any action planned here? I just noticed I was using both in my code and changed it and then realized it was actually inconsistent in the library itself.

**Comment by paulirish** [comment]
Fixed!  I kept the misspelled class in there so if you have any existing styling or selector references they'll still apply. 

Maybe in a few years we'll remove that in a breaking release. Maybe not.

**Comment by theRealPadster** [comment]
Thanks, that was fast! Would you be able to do a patch release (0.3.4) on NPM so I can pull it into my project?
