### ISSUE TITLE
Using lite-youtube with Google Tag Manager

### ISSUE THREAD

**Issue by Fiorinol** [paulirish/lite-youtube-embed#69]
Hi, I'm having issues with the JS API with GTM.

I had the following HTML which worked fine with my GTM installation and its current triggers:

`<iframe src="https://www.youtube.com/embed/<?= $video_id ?>?enablejsapi=1"> </iframe>`

Then I implemented lite-youtube and I have the following HTML on my website:

```
<lite-youtube videoid="<?= $video_id ?>" style="background-image: url('https://i.ytimg.com/vi/<?= $video_id ?>/hqdefault.jpg');" params="enablejsapi=1">
	<button type="button" class="lty-playbtn" title=""></button>
</lite-youtube>
```

Unless I load "https://www.youtube.com/iframe_api" on the page itself, my GTM triggers don't trigger. I can load it below the fold, so it's not that big a deal, but in that case, should I even add "enablejsapi=1" to the parameters, or is there a way to make it work natively with GTM?

**Comment by radum** [comment]
AFAIK unless you load `https://www.youtube.com/iframe_api`before GTM it will not trigger. It will have to be there.

**Comment by paulirish** [comment]
Tricky stuff but this is outside the scope of the support I can provide.

Thanks Radu for chiming in. :)   And looks like these folks encountered similar stuff: https://github.com/greenpeace/planet4/issues/179
