### ISSUE TITLE
Use the best thumbnail/placeholder/cover image available

### ISSUE THREAD

**Issue by paulirish** [paulirish/lite-youtube-embed#70]
I've captured the general problem here: https://github.com/paulirish/lite-youtube-embed/blob/master/youtube-thumbnail-urls.md

Two things we can do:

* [ ] Do the sddefault->hqdefault fallback
    - When doing this, apply referrerpolicy (https://github.com/ampproject/amphtml/pull/3940)
* [ ] Consider using webp if supported, falling back to jpg

A few other bugs have touched on this mostly #54

**Comment by zachleat** [comment]
I don’t think it makes sense to include in this plugin code but I’ll just mention another option I use to see if it sparks anything—I use the OpenGraph image for the video URL! Some detail here https://www.zachleat.com/web/youtube-embeds/#higher-quality-posters
