### ISSUE TITLE
Camel-case of property in main page's s doc

### ISSUE THREAD

**Issue by gonzalo-roberto-diaz** [paulirish/lite-youtube-embed#77]
In the **Pro-Usage** section

`<lite-youtube videoid="ogfYd705cRs" `

I believe that property should be **_videoId_** (with capital "I")

**Comment by paulirish** [comment]
nah.. html attributes are lowercase by convention.

but ... if someone set this html attribute as camel-case everything would still work because `elem.getAttribute('videoid')` will read the attribute value, even though the attribute name isn't a case-sensitive match.

:)
