### ISSUE TITLE
Use as background video

### ISSUE THREAD

**Issue by mad-gav** [paulirish/lite-youtube-embed#84]
Can this plugin be used for youtube videos that are used in backgrounds?

**Comment by Garbee** [comment]
Background are generally not interactive. This plugin explicitly requires a user interaction to initiate the video load.

I'd say for backgrounds the usage of the embed will very much depend greatly between apps and pages. Meaning a more thoughtful hands-on coding approach should be used.

**Comment by paulirish** [comment]
for full bleed background video you'd probably just want the normal iframe...

```html
<iframe allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen src="https://www.youtube-nocookie.com/embed/ogfYd705cRs?autoplay=1"></iframe>
```

... and some CSS to style how you want it. using lite-youtube-embed doesnt make a lot of sense for this usecase
