### ISSUE TITLE
Shadow Gradient Across Top Of Player

### ISSUE THREAD

**Issue by ewwwgiddings** [paulirish/lite-youtube-embed#91]
What's the shadow gradient that shows over the top of the background image for? Is there supposed to be a title here? Am I missing a property? Looks like a bug. I'm using Angular 10. It's this in the CSS and I don't see anything reference it in the JS to add a title:

`lite-youtube::before {
    content: '';
    display: block;
    position: absolute;
    top: 0;
    background-image: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAADGCAYAAAAT+OqFAAAAdklEQVQoz42QQQ7AIAgEF/T/D+kbq/RWAlnQyyazA4aoAB4FsBSA/bFjuF1EOL7VbrIrBuusmrt4ZZORfb6ehbWdnRHEIiITaEUKa5EJqUakRSaEYBJSCY2dEstQY7AuxahwXFrvZmWl2rh4JZ07z9dLtesfNj5q0FU3A5ObbwAAAABJRU5ErkJggg==);
    background-position: top;
    background-repeat: repeat-x;
    height: 60px;
    padding-bottom: 50px;
    width: 100%;
    transition: all 0.2s cubic-bezier(0, 0, 0.2, 1);
} `

**Comment by ewwwgiddings** [comment]
It happens when using the "Pro Usage"

**Comment by paulirish** [comment]
It's replicating the same appearance you see in the real youtube embed:

<img width="1374" alt="image" src="https://user-images.githubusercontent.com/39191/143786611-79c4b339-7035-4eea-a387-b61b61c30657.png">
