### ISSUE TITLE
render blocking resources

### ISSUE THREAD

**Issue by nemecky** [paulirish/lite-youtube-embed#93]
Hi, we're using this on a Shopify store and it has definitely improved the performance scores, but I noticed the assets are showing up as render blocking in the test results and waterfall charts.  So far our developer hasn't had any luck trying stop that from happening, so I thought I'd check here and see if anyone has any suggestions? Thanks!

**Comment by Garbee** [comment]
Which assets exactly are showing as render blocking?

**Comment by nemecky** [comment]
Sorry I had no clue you replied to my comment! It was the CSS file but we sorted it out by adding preload to it. Thanks for the reply and apologies for the extremely late response.
