### ISSUE TITLE
LIVE STREAM - no autoplay

### ISSUE THREAD

**Issue by pir8radio** [paulirish/lite-youtube-embed#96]
seems to work for youtube live even though I don't see much talk of this..     However in any browser, once you hit the lite-youtube play button, it then brings up the standard youtube play button, clicking that finally starts playback.     any suggestions?  THanks.

**Comment by pir8radio** [comment]
humm   maybe this is my issue, looks like a standard video wont auto play on desktop either...   ill dig into the settings.

**Comment by paulirish** [comment]
dupe of #6
